import type { InkStoryData } from 'libs/entities'

const storyContent: InkStoryData = {
    inkVersion: 21,
    root: [
        ['\n', { '->': 'start' }, ['done', { '#f': 5, '#n': 'g-0' }], null],
        'done',
        {
            start: [
                [
                    'ev',
                    { 'x()': 'get_player_name' },
                    '/ev',
                    { 'VAR=': 'player_name', re: true },
                    '\n',
                    '^“When countless mouths are sated with innocent blood, ',
                    '#',
                    '^style italicText centralizedText',
                    '/#',
                    '\n',
                    '^The Abyss shall breathe its curse — ash, corruption, void — ',
                    '#',
                    '^style italicText centralizedText',
                    '/#',
                    '\n',
                    '^To blacken guardian rings of life, ',
                    '#',
                    '^style italicText centralizedText',
                    '/#',
                    '\n',
                    "^Until Seven Thrones crack and crash from heaven's height. ",
                    '#',
                    '^style italicText centralizedText',
                    '/#',
                    '\n',
                    '^Then, from the weeping ground, ',
                    '#',
                    '^style italicText centralizedText',
                    '/#',
                    '\n',
                    '^The Shadowed One shall raise its silent crown, ',
                    '#',
                    '^style italicText centralizedText',
                    '/#',
                    '\n',
                    '^And claim the shattered world as darkness drowns.” ',
                    '#',
                    '^style italicText centralizedText',
                    '/#',
                    '\n',
                    '^The hue of the setting sun, nearly swallowed by night, blended with the swamp’s dark greens, staining the stagnant waters. Will-o’-wisps, like fragments of the cursed prophecy, broke free from the murk and began their ghostly dance above the sludge. A biting cold — far beyond twilight — enveloped the group, heavy with the stink of rot, sulfur, and decay. ',
                    '#',
                    '^style topDivider',
                    '/#',
                    '\n',
                    '^Lysandra’s eyes blazed, nostrils flared.',
                    '\n',
                    '^“To hell with this prophecy! Protaxios, gather the stealthiest soldiers and scout the nearby swamps. Renpet-Ib, raise magical barriers around the village. We need more troops. I’ll go to the Citadel myself to bargain with some noble.”',
                    '\n',
                    '^As she shouted, you saw her tremble — and felt your own palms sweat.',
                    '\n',
                    'ev',
                    'str',
                    '^“Commander, Let me join you at the Citadel.”',
                    '/str',
                    '/ev',
                    { '*': '.^.c-0', flg: 20 },
                    [
                        'ev',
                        { '^->': 'start.0.57.$r1' },
                        { 'temp=': '$r' },
                        'str',
                        { '->': '.^.s' },
                        [{ '#n': '$r1' }],
                        '/str',
                        '/ev',
                        { '*': '.^.^.c-1', flg: 18 },
                        {
                            s: [
                                '^“I can move quietly, Protaxios. Let me scout with you.” ',
                                '#',
                                '^prop isDisabled',
                                '/#',
                                { '->': '$r', var: true },
                                null
                            ]
                        }
                    ],
                    [
                        'ev',
                        { '^->': 'start.0.58.$r1' },
                        { 'temp=': '$r' },
                        'str',
                        { '->': '.^.s' },
                        [{ '#n': '$r1' }],
                        '/str',
                        '/ev',
                        { '*': '.^.^.c-2', flg: 18 },
                        {
                            s: [
                                '^“The village needs every blade. I stand with Renpet-Ib.” ',
                                '#',
                                '^prop isDisabled',
                                '/#',
                                { '->': '$r', var: true },
                                null
                            ]
                        }
                    ],
                    {
                        'c-0': [
                            '\n',
                            { '->': 'courtly_intrigue' },
                            { '#f': 5 }
                        ],
                        'c-1': [
                            'ev',
                            { '^->': 'start.0.c-1.$r2' },
                            '/ev',
                            { 'temp=': '$r' },
                            { '->': '.^.^.57.s' },
                            [{ '#n': '$r2' }],
                            '\n',
                            'end',
                            { '#f': 5 }
                        ],
                        'c-2': [
                            'ev',
                            { '^->': 'start.0.c-2.$r2' },
                            '/ev',
                            { 'temp=': '$r' },
                            { '->': '.^.^.58.s' },
                            [{ '#n': '$r2' }],
                            '\n',
                            'end',
                            { '#f': 5 }
                        ]
                    }
                ],
                { '#f': 1 }
            ],
            courtly_intrigue: [
                'ev',
                'str',
                '^hero_0002',
                '/str',
                { 'x()': 'add_to_hero_party', exArgs: 1 },
                'out',
                '/ev',
                '\n',
                'ev',
                'str',
                '^Riding horse',
                '/str',
                'str',
                '^hero_0001',
                '/str',
                'str',
                '^heroes',
                '/str',
                { 'x()': 'add_mount', exArgs: 3 },
                'out',
                '/ev',
                '\n',
                'ev',
                'str',
                '^Riding horse',
                '/str',
                'str',
                '^hero_0002',
                '/str',
                'str',
                '^heroes',
                '/str',
                { 'x()': 'add_mount', exArgs: 3 },
                'out',
                '/ev',
                '\n',
                '^“Commander, Let me join you at the Citadel.” You asked her, and she nodded. ',
                '#',
                '^style topDivider',
                '/#',
                '\n',
                '^The sky deepened to indigo as stars slowly awakened. The southern road — the only path to the Citadel — narrowed, with few places to camp. Ancient trees leaned toward the path as if trying to delay travelers.',
                '\n',
                '^Lysandra rode ahead, refusing an escort — only you, her new recruit, followed.',
                '\n',
                '^“Protect the village!”',
                '\n',
                '^She yelled to the soldiers.',
                '\n',
                '^The weight of her choices echoed in your mind. Ahead in the forest, gleaming eyes tracked you.',
                '\n',
                '^After hours of travel, Lysandra ordered a halt. She set up a makeshift camp between the road and a cluster of rocks.',
                '\n',
                '^You’d barely shared sparse rations when unnatural heat surged — first, just the rustle of dry leaves. Then, sharp, rapid hisses multiplied in the darkness as fiery shapes approached.',
                '\n',
                '^“An ambush!”',
                '\n',
                '^Lysandra growled.',
                '\n',
                '^From the shadows, four blazefen — salamander-men with amber eyes and flaming tongues — attacked. To everyone’s shock, one hurled a spear toward the horses, missing by inches. Lysandra saw their intent.',
                '\n',
                '^“',
                'ev',
                { 'VAR?': 'player_name' },
                'out',
                '/ev',
                '^, Protect the mounts!”',
                '\n',
                '^Could word of Lysandra’s movements have leaked? Were there spies in the village? What seemed a random attack now had a clear goal: delay her rush to the Citadel.',
                '\n',
                'ev',
                'str',
                '^blazefen_ambush_01',
                '/str',
                '/ev',
                { 'temp=': 'combat_id' },
                'ev',
                { 'VAR?': 'combat_id' },
                '/ev',
                { '->t->': 'combat_scene' },
                'ev',
                { 'VAR?': 'combat_id' },
                { 'x()': 'get_combat_result', exArgs: 1 },
                '/ev',
                { 'temp=': 'combat_result' },
                '\n',
                'ev',
                { 'VAR?': 'combat_result' },
                '/ev',
                [
                    'du',
                    'ev',
                    -1,
                    '==',
                    '/ev',
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            'pop',
                            '\n',
                            { '->t->': 'defeat_scene' },
                            'end',
                            { '->': '.^.^.^.94' },
                            null
                        ]
                    }
                ],
                [
                    'du',
                    'ev',
                    0,
                    '==',
                    '/ev',
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            'pop',
                            '\n',
                            { '->t->': 'draw_scene' },
                            'end',
                            { '->': '.^.^.^.94' },
                            null
                        ]
                    }
                ],
                [
                    'du',
                    'ev',
                    1,
                    '==',
                    '/ev',
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            'pop',
                            '\n',
                            { '->t->': 'consequence_scene' },
                            'end',
                            { '->': '.^.^.^.94' },
                            null
                        ]
                    }
                ],
                [
                    'du',
                    'ev',
                    2,
                    '==',
                    '/ev',
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            'pop',
                            '\n',
                            { '->t->': 'consequence_scene' },
                            'end',
                            { '->': '.^.^.^.94' },
                            null
                        ]
                    }
                ],
                'pop',
                'nop',
                '\n',
                { '#f': 1 }
            ],
            defeat_scene: [
                '^Your vision blurs as you collapse to the ground. The clatter of your falling weapon echoes in your ears before darkness consumes you.',
                '\n',
                'end',
                { '#f': 1 }
            ],
            draw_scene: [
                '^Panting heavily, you lock eyes with your opponent across the bloodied ground. Both of you stand trembling, weapons lowered in unspoken agreement - neither can land a decisive blow.',
                '\n',
                'ev',
                'void',
                '/ev',
                '->->',
                { '#f': 1 }
            ],
            add_mount: [
                { 'temp=': 'character_team' },
                { 'temp=': 'character_id' },
                { 'temp=': 'mount_name' },
                'ev',
                { 'VAR?': 'mount_name' },
                'out',
                '/ev',
                '^ - ',
                'ev',
                { 'VAR?': 'character_id' },
                'out',
                '/ev',
                '^ - ',
                'ev',
                { 'VAR?': 'character_team' },
                'out',
                '/ev',
                '\n',
                { '#f': 1 }
            ],
            add_to_hero_party: [
                { 'temp=': 'hero_id' },
                'ev',
                { 'VAR?': 'hero_id' },
                'out',
                '/ev',
                '\n',
                { '#f': 1 }
            ],
            ai_action: ['^ai acting', '\n', { '#f': 1 }],
            attack: [
                { 'temp=': 'character_id' },
                '^attacking ',
                'ev',
                { 'VAR?': 'character_id' },
                'out',
                '/ev',
                '\n',
                { '#f': 1 }
            ],
            end_turn: ['ev', 0, '/ev', '~ret', { '#f': 1 }],
            get_action_result: [
                { 'temp=': 'reverse_log_position' },
                'ev',
                'str',
                '^Action result',
                '/str',
                '/ev',
                '~ret',
                { '#f': 1 }
            ],
            get_alive_characters_size: ['ev', 1, '/ev', '~ret', { '#f': 1 }],
            get_character_info: [
                { 'temp=': 'prop' },
                { 'temp=': 'index' },
                { 'temp=': 'team' },
                'ev',
                1,
                '/ev',
                '~ret',
                { '#f': 1 }
            ],
            get_combat_result: [
                { 'temp=': 'combat_id' },
                'ev',
                1,
                '/ev',
                '~ret',
                { '#f': 1 }
            ],
            get_combat_round: ['ev', 1, '/ev', '~ret', { '#f': 1 }],
            get_combat_status: [
                'ev',
                'str',
                '^VICTORY',
                '/str',
                '/ev',
                '~ret',
                { '#f': 1 }
            ],
            get_mount_info: [
                { 'temp=': 'prop' },
                { 'temp=': 'character_id' },
                'ev',
                1,
                '/ev',
                '~ret',
                { '#f': 1 }
            ],
            get_party_size: [
                { 'temp=': 'team' },
                'ev',
                1,
                '/ev',
                '~ret',
                { '#f': 1 }
            ],
            get_player_name: [
                'ev',
                'str',
                '^Celcius',
                '/str',
                '/ev',
                '~ret',
                { '#f': 1 }
            ],
            is_player_action: ['ev', true, '/ev', '~ret', { '#f': 1 }],
            set_combat: [
                { 'temp=': 'combat_id' },
                'ev',
                { 'VAR?': 'combat_id' },
                'out',
                '/ev',
                '\n',
                { '#f': 1 }
            ],
            combat_scene: [
                { 'temp=': 'combat_id' },
                '#',
                '^style topDivider',
                '/#',
                'ev',
                { 'VAR?': 'combat_id' },
                { 'x()': 'set_combat', exArgs: 1 },
                'pop',
                '/ev',
                '\n',
                '^⚔️ COMBAT STARTED ⚔️ ',
                '#',
                '^style centralizedText',
                '/#',
                '\n',
                { '->t->': 'combat_loop' },
                '^🏆 COMBAT ENDED 🏆 ',
                '#',
                '^style centralizedText',
                '/#',
                '\n',
                'ev',
                'void',
                '/ev',
                '->->',
                { '#f': 1 }
            ],
            combat_loop: [
                '#',
                '^event turn start',
                '/#',
                '^🌀 ROUND ',
                'ev',
                { 'x()': 'get_combat_round' },
                'out',
                '/ev',
                '\n',
                '^ENEMIES',
                '\n',
                'ev',
                0,
                '/ev',
                { '->t->': 'enemy_loop' },
                '^PARTY',
                '\n',
                'ev',
                0,
                '/ev',
                { '->t->': 'hero_loop' },
                '^📜 Combat Log',
                '\n',
                'ev',
                { 'x()': 'get_alive_characters_size' },
                1,
                '-',
                '/ev',
                { 'temp=': 'log_size' },
                '\n',
                'ev',
                { 'VAR?': 'log_size' },
                '/ev',
                { '->t->': 'combat_log_loop' },
                'ev',
                { 'x()': 'is_player_action' },
                '_',
                '/ev',
                [
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            '\n',
                            { '->t->': 'player_action_options' },
                            { '->': '.^.^.^.40' },
                            null
                        ]
                    }
                ],
                [
                    { '->': '.^.b' },
                    {
                        b: [
                            '\n',
                            'ev',
                            { 'x()': 'ai_action' },
                            'out',
                            '/ev',
                            '\n',
                            { '->': '.^.^.^.40' },
                            null
                        ]
                    }
                ],
                'nop',
                '\n',
                'ev',
                { 'x()': 'end_turn' },
                'out',
                '/ev',
                '\n',
                '#',
                '^event turn end',
                '/#',
                'ev',
                { 'x()': 'get_combat_status' },
                'str',
                '^IN_PROGRESS',
                '/str',
                '==',
                '/ev',
                [
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            '\n',
                            { '->': '.^.^.^' },
                            { '->': '.^.^.^.58' },
                            null
                        ]
                    }
                ],
                'nop',
                '\n',
                'ev',
                'void',
                '/ev',
                '->->',
                { '#f': 1 }
            ],
            enemy_loop: [
                { 'temp=': 'index' },
                'ev',
                { 'VAR?': 'index' },
                'str',
                '^enemies',
                '/str',
                { 'x()': 'get_party_size', exArgs: 1 },
                '>=',
                '/ev',
                [
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            '^ ',
                            'ev',
                            'void',
                            '/ev',
                            '->->',
                            { '->': '.^.^.^.10' },
                            null
                        ]
                    }
                ],
                'nop',
                '\n',
                'ev',
                'str',
                '^enemies',
                '/str',
                { 'VAR?': 'index' },
                'str',
                '^id',
                '/str',
                { 'x()': 'get_character_info', exArgs: 3 },
                '/ev',
                { 'temp=': 'enemy_id' },
                '\n',
                'ev',
                'str',
                '^enemies',
                '/str',
                { 'VAR?': 'index' },
                'str',
                '^name',
                '/str',
                { 'x()': 'get_character_info', exArgs: 3 },
                '/ev',
                { 'temp=': 'enemy_name' },
                '\n',
                'ev',
                'str',
                '^enemies',
                '/str',
                { 'VAR?': 'index' },
                'str',
                '^hp',
                '/str',
                { 'x()': 'get_character_info', exArgs: 3 },
                '/ev',
                { 'temp=': 'enemy_hp' },
                '\n',
                'ev',
                { 'VAR?': 'enemy_hp' },
                0,
                '>',
                '/ev',
                [
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            '\n',
                            '^☠️ ',
                            'ev',
                            { 'VAR?': 'enemy_name' },
                            'out',
                            '/ev',
                            '^ HP: ',
                            'ev',
                            { 'VAR?': 'enemy_hp' },
                            'out',
                            '/ev',
                            '^ ',
                            '#',
                            '^style monospaceText',
                            '/#',
                            '\n',
                            'ev',
                            { 'VAR?': 'enemy_id' },
                            '/ev',
                            { '->t->': 'mount_display' },
                            { '->': '.^.^.^.54' },
                            null
                        ]
                    }
                ],
                'nop',
                '\n',
                'ev',
                { 'VAR?': 'index' },
                1,
                '+',
                '/ev',
                { '->': '.^' },
                { '#f': 1 }
            ],
            hero_loop: [
                { 'temp=': 'index' },
                'ev',
                { 'VAR?': 'index' },
                'str',
                '^heroes',
                '/str',
                { 'x()': 'get_party_size', exArgs: 1 },
                '>=',
                '/ev',
                [
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            '^ ',
                            'ev',
                            'void',
                            '/ev',
                            '->->',
                            { '->': '.^.^.^.10' },
                            null
                        ]
                    }
                ],
                'nop',
                '\n',
                'ev',
                'str',
                '^heroes',
                '/str',
                { 'VAR?': 'index' },
                'str',
                '^id',
                '/str',
                { 'x()': 'get_character_info', exArgs: 3 },
                '/ev',
                { 'temp=': 'hero_id' },
                '\n',
                'ev',
                'str',
                '^heroes',
                '/str',
                { 'VAR?': 'index' },
                'str',
                '^name',
                '/str',
                { 'x()': 'get_character_info', exArgs: 3 },
                '/ev',
                { 'temp=': 'hero_name' },
                '\n',
                'ev',
                'str',
                '^heroes',
                '/str',
                { 'VAR?': 'index' },
                'str',
                '^hp',
                '/str',
                { 'x()': 'get_character_info', exArgs: 3 },
                '/ev',
                { 'temp=': 'hero_hp' },
                '\n',
                '^🛡️ ',
                'ev',
                { 'VAR?': 'hero_name' },
                'out',
                '/ev',
                '^ HP: ',
                'ev',
                { 'VAR?': 'hero_hp' },
                'out',
                '/ev',
                '^ ',
                '#',
                '^style monospaceText',
                '/#',
                '\n',
                'ev',
                { 'VAR?': 'hero_id' },
                '/ev',
                { '->t->': 'mount_display' },
                'ev',
                { 'VAR?': 'index' },
                1,
                '+',
                '/ev',
                { '->': '.^' },
                { '#f': 1 }
            ],
            mount_display: [
                { 'temp=': 'character_id' },
                'ev',
                { 'VAR?': 'character_id' },
                'str',
                '^hp',
                '/str',
                { 'x()': 'get_mount_info', exArgs: 2 },
                '/ev',
                { 'temp=': 'mount_hp' },
                '\n',
                'ev',
                { 'VAR?': 'mount_hp' },
                0,
                '>',
                '/ev',
                [
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            '\n',
                            '^└─ 🐴 HP: ',
                            'ev',
                            { 'VAR?': 'mount_hp' },
                            'out',
                            '/ev',
                            '^  ',
                            '#',
                            '^style monospaceText',
                            '/#',
                            '\n',
                            { '->': '.^.^.^.16' },
                            null
                        ]
                    }
                ],
                'nop',
                '\n',
                'ev',
                'void',
                '/ev',
                '->->',
                { '#f': 1 }
            ],
            combat_log_loop: [
                { 'temp=': 'index' },
                'ev',
                { 'VAR?': 'index' },
                0,
                '<',
                '/ev',
                [
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            '^ ',
                            'ev',
                            'void',
                            '/ev',
                            '->->',
                            { '->': '.^.^.^.7' },
                            null
                        ]
                    }
                ],
                'nop',
                '\n',
                'ev',
                { 'VAR?': 'index' },
                { 'x()': 'get_action_result', exArgs: 1 },
                'out',
                '/ev',
                '\n',
                'ev',
                { 'VAR?': 'index' },
                1,
                '-',
                '/ev',
                { '->': '.^' },
                { '#f': 1 }
            ],
            player_action_options: [
                '^Select an enemy to attack',
                '\n',
                'ev',
                0,
                '/ev',
                { '->': 'enemy_choice_loop' },
                { '#f': 1 }
            ],
            enemy_choice_loop: [
                { 'temp=': 'index' },
                'ev',
                'str',
                '^enemies',
                '/str',
                { 'VAR?': 'index' },
                'str',
                '^name',
                '/str',
                { 'x()': 'get_character_info', exArgs: 3 },
                '/ev',
                { 'temp=': 'enemy_name' },
                '\n',
                'ev',
                'str',
                '^enemies',
                '/str',
                { 'VAR?': 'index' },
                'str',
                '^hp',
                '/str',
                { 'x()': 'get_character_info', exArgs: 3 },
                '/ev',
                { 'temp=': 'enemy_hp' },
                '\n',
                'ev',
                'str',
                '^enemies',
                '/str',
                { 'VAR?': 'index' },
                'str',
                '^id',
                '/str',
                { 'x()': 'get_character_info', exArgs: 3 },
                '/ev',
                { 'temp=': 'enemy_id' },
                '\n',
                'ev',
                { 'VAR?': 'enemy_hp' },
                0,
                '>',
                '/ev',
                [
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            '\n',
                            'ev',
                            'str',
                            'ev',
                            { 'VAR?': 'enemy_name' },
                            'out',
                            '/ev',
                            '/str',
                            '/ev',
                            { '*': '.^.c-0', flg: 4 },
                            { '->': '.^.^.^.43' },
                            {
                                'c-0': [
                                    '\n',
                                    'ev',
                                    { 'VAR?': 'enemy_id' },
                                    { 'x()': 'attack', exArgs: 1 },
                                    'pop',
                                    '/ev',
                                    '\n',
                                    'ev',
                                    'void',
                                    '/ev',
                                    '->->',
                                    { '#f': 5 }
                                ]
                            }
                        ]
                    }
                ],
                'nop',
                '\n',
                'ev',
                { 'VAR?': 'index' },
                'str',
                '^enemies',
                '/str',
                { 'x()': 'get_party_size', exArgs: 1 },
                1,
                '-',
                '<',
                '/ev',
                [
                    { '->': '.^.b', c: true },
                    {
                        b: [
                            '^ ',
                            'ev',
                            { 'VAR?': 'index' },
                            1,
                            '+',
                            '/ev',
                            { '->': '.^.^.^' },
                            { '->': '.^.^.^.56' },
                            null
                        ]
                    }
                ],
                'nop',
                '\n',
                { '#f': 1 }
            ],
            consequence_scene: [
                [
                    '^The acrid smell of ozone and blood hangs heavy in the air. Among the fallen, something glints. ',
                    '#',
                    '^style topDivider',
                    '/#',
                    '\n',
                    '^You find:',
                    '\n',
                    '^*   23 Gold Crowns',
                    '\n',
                    '^*   A minor Healing Potion',
                    '\n',
                    [
                        'ev',
                        { '^->': 'consequence_scene.0.11.$r1' },
                        { 'temp=': '$r' },
                        'str',
                        { '->': '.^.s' },
                        [{ '#n': '$r1' }],
                        '/str',
                        '/ev',
                        { '*': '.^.^.c-0', flg: 2 },
                        { s: ['^Continue ', { '->': '$r', var: true }, null] }
                    ],
                    {
                        'c-0': [
                            'ev',
                            { '^->': 'consequence_scene.0.c-0.$r2' },
                            '/ev',
                            { 'temp=': '$r' },
                            { '->': '.^.^.11.s' },
                            [{ '#n': '$r2' }],
                            'ev',
                            'void',
                            '/ev',
                            '->->',
                            '\n',
                            { '#f': 5 }
                        ]
                    }
                ],
                { '#f': 1 }
            ],
            'global decl': [
                'ev',
                'str',
                '^',
                '/str',
                { 'VAR=': 'player_name' },
                '/ev',
                'end',
                null
            ],
            '#f': 1
        }
    ],
    listDefs: {}
}

export default storyContent

